# Generated by Django 4.2.16 on 2026-03-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='joblisting',
            new_name='jobs_joblis_url_4dfc46_idx',
            old_name='jobs_joblis_url_idx',
        ),
        migrations.RenameIndex(
            model_name='joblisting',
            new_name='jobs_joblis_source_8b426c_idx',
            old_name='jobs_joblis_source_idx',
        ),
        migrations.RenameIndex(
            model_name='joblisting',
            new_name='jobs_joblis_is_acti_861fa0_idx',
            old_name='jobs_joblis_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='joblisting',
            new_name='jobs_joblis_scraped_91511e_idx',
            old_name='jobs_joblis_scraped_idx',
        ),
        migrations.RenameIndex(
            model_name='joblisting',
            new_name='jobs_joblis_job_typ_265f24_idx',
            old_name='jobs_joblis_job_typ_idx',
        ),
        migrations.RenameIndex(
            model_name='joblisting',
            new_name='jobs_joblis_experie_ec2b7a_idx',
            old_name='jobs_joblis_exp_lev_idx',
        ),
        migrations.RenameIndex(
            model_name='joblisting',
            new_name='jobs_joblis_is_remo_3a1ea1_idx',
            old_name='jobs_joblis_is_remo_idx',
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
