# Generated by Django 4.2.16 on 2026-03-15 12:09
# 
# 
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cvupload',
            new_name='cv_analyzer_user_id_4125d5_idx',
            old_name='cv_analyze_user_id_idx',
        ),
    ]
